#!/bin/bash

USERNAME=username
REMOTE_HOSTNAME=hostname.com
REMOTE_DIR=/some/dir/here
SSH_KEY="-i mykey.pub"

/usr/bin/rsync -avz -e ssh ../controllers $USERNAME@$REMOTE_HOSTNAME:$REMOTE_DIR
/usr/bin/rsync -avz -e ssh ../htdocs $USERNAME@$REMOTE_HOSTNAME:$REMOTE_DIR
/usr/bin/rsync -avz -e ssh ../lib $USERNAME@$REMOTE_HOSTNAME:$REMOTE_DIR
