#!/bin/bash
#
# Copyright (c) 2011 Nicholas Granado
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
#
REMOTE_HOSTNAME=your.servername.here
echo "pushing code to $REMOTE_HOSTNAME ...";
WEB_SERVER_USERNAME=www-data
USERNAME=www-data
SSH_KEY="your ssh key here"
REMOTE_DIR=/var/www/application/www/htdocs

CACHE_DIR=../cache
CONTROLLERS_DIR=../controllers
HTDOCS_DIR=../htdocs
LIB_DIR=../lib
VIEWS_DIR=../views

echo "resetting ownership ...";
/usr/bin/ssh -i $SSH_KEY $USERNAME@$REMOTE_HOSTNAME "sudo chown -R $USERNAME:$USERNAME $REMOTE_DIR/"
echo "purging smarty cache ...";
/usr/bin/ssh -i $SSH_KEY $USERNAME@$REMOTE_HOSTNAME "cd $REMOTE_DIR/views/smarty/templates_c/; sudo rm *.php;"
echo "purging rainbow-php cache ...";
/usr/bin/ssh -i $SSH_KEY $USERNAME@$REMOTE_HOSTNAME "cd $REMOTE_DIR/cache/; sudo rm *.apc;"
echo "rsync'ing ...";
/usr/bin/rsync -avz -e "ssh -i $SSH_KEY" $VIEWS_DIR $LIB_DIR $HTDOCS_DIR $CONTROLLERS_DIR $CACHE_DIR $USERNAME@$REMOTE_HOSTNAME:$REMOTE_DIR/
echo "setting ownership ...";
/usr/bin/ssh -i $SSH_KEY $USERNAME@$REMOTE_HOSTNAME "sudo chown -R $WEB_SERVER_USERNAME:$WEB_SERVER_USERNAME $REMOTE_DIR/"